### ISSUE TITLE
Fix Stadia - Community Guidelines

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/sandbox#222]
This document is no longer properly tracked.

`InaccessibleContentError: The document cannot be accessed or its content can not be selected:
 - Encoding not recognized: 'IE=edge' (searched as: 'ieedge')`

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Stadia&documentType=Community%20Guidelines&expertMode=true).

And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Stadia.json).

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked.

`InaccessibleContentError: The document cannot be accessed or its content can not be selected:
 - Encoding not recognized: 'IE=edge' (searched as: 'ieedge')`

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Stadia&documentType=Community%20Guidelines&expertMode=true).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Stadia.json).

**Comment by Ndpnt** [comment]
🤖 Closed automatically as version is unchanged but data has been fetched correctly
