### ISSUE TITLE
Fix Facebook - Privacy Policy

### ISSUE THREAD

**Issue by Ndpnt** [OpenTermsArchive/sandbox#69]
This service is not available anymore.
  Please fix it.

  `InaccessibleContentError: The document cannot be accessed or its content can not be selected: Navigation timeout of 30000 ms exceeded`

  Here some ideas on how to fix this issue:
  - See what's wrong online: https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=._5tko&selectedCss[]=div%5Brole%3D%22main%22%5D&expertMode=true
  - Or on your local: http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=._5tko&selectedCss[]=div%5Brole%3D%22main%22%5D&expertMode=true
  

  And some info about what has already been tracked
  - See original JSON file: https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json

  Thanks

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

  This service is not available anymore.
  Please fix it.

  `InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector "" has no match in the web page at 'undefined'`

  Here some ideas on how to fix this issue:
  - See what's wrong online: https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  - Or on your local: http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  

  And some info about what has already been tracked
  - See original JSON file: https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json

  Thanks

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

  This service is not available anymore.
  Please fix it.

  `InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector "" has no match in the web page at 'undefined'`

  Here some ideas on how to fix this issue:
  - See what's wrong online: https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  - Or on your local: http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  

  And some info about what has already been tracked
  - See original JSON file: https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json

  Thanks

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

  This service is not available anymore.
  Please fix it.

  `InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector ".derp" has no match in the web page at 'https://fr-fr.facebook.com/privacy/explanation/'`

  Here some ideas on how to fix this issue:
  - See what's wrong online: https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=._5tko&selectedCss[]=.derp&expertMode=true
  - Or on your local: http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=._5tko&selectedCss[]=.derp&expertMode=true
  

  And some info about what has already been tracked
  - See original JSON file: https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json

  Thanks

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

  This service is not available anymore.
  Please fix it.

  `InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector "div[role="main"]" has no match in the web page at 'https://fr-fr.facebook.com/privacy/explanation/'`

  Here some ideas on how to fix this issue:
  - See what's wrong online: https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  - Or on your local: http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=undefined&name=Facebook&documentType=Privacy%20Policy&expertMode=true
  

  And some info about what has already been tracked
  - See original JSON file: https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json

  Thanks

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by martinratinaud** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked.

`InaccessibleContentError: The document cannot be accessed or its content can not be selected: The provided selector "._5tkp" has no match in the web page at 'https://www.facebook.com/about/privacy'`

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Fwww.facebook.com%2Fabout%2Fprivacy&name=Facebook&documentType=Privacy%20Policy&selectedCss[]=._5tkp&expertMode=true).
- Using the [local contribution tool](http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Fwww.facebook.com%2Fabout%2Fprivacy&name=Facebook&documentType=Privacy%20Policy&selectedCss[]=._5tkp&expertMode=true). See [Setup Guide](https://github.com/OpenTermsArchive/contribution-tool#usage).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json).

**Comment by Ndpnt** [comment]
🤖 Closed automatically as data was gathered successfully

**Comment by martinratinaud** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked.

`InaccessibleContentError: The document cannot be accessed or its content can not be selected: The "start" selector has no match in document in: {"startBefore":"[role=\"separator\"]","endAfter":"body"}`

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=%5Bobject%20Object%5D&selectedCss[]=div%5Brole%3D%22main%22%5D&expertMode=true).
- Using the [local contribution tool](http://localhost:3000/en/service?destination=OpenTermsArchive%2Fsandbox&step=2&url=https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F&name=Facebook&documentType=Privacy%20Policy&removedCss[]=%5Bobject%20Object%5D&selectedCss[]=div%5Brole%3D%22main%22%5D&expertMode=true). See [Setup Guide](https://github.com/OpenTermsArchive/contribution-tool#usage).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json).

**Comment by martinratinaud** [comment]
🤖 Closed automatically as version is unchanged but data has been fetched correctly

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked.


```
InaccessibleContentError: The document cannot be accessed or its content can not be selected:
 - test
```

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?json=%7B%22name%22%3A%22Facebook%22%2C%22documents%22%3A%7B%22Privacy+Policy%22%3A%7B%22fetch%22%3A%22https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F%22%2C%22select%22%3A%5B%22hr%2Bdiv%22%5D%2C%22filter%22%3A%5B%22removeEmptyAnchorsLinks%22%2C%22removeTrackingIDs%22%2C%22removeLocaleFromUrls%22%2C%22prefixUrlToFrenchVersions%22%5D%2C%22executeClientScripts%22%3Atrue%7D%7D%7D&destination=OpenTermsArchive%2Fsandbox&expertMode=true&step=2).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json).

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked.


```
InaccessibleContentError: The document cannot be accessed or its content can not be selected:
 - Timed out after 30 seconds when trying to fetch 'http://www.shockwave.com/about/privacyPolicy.jsp'
```

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?json=%7B%22name%22%3A%22Facebook%22%2C%22documents%22%3A%7B%22Privacy+Policy%22%3A%7B%22fetch%22%3A%22https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F%22%2C%22select%22%3A%5B%22hr%2Bdiv%22%5D%2C%22filter%22%3A%5B%22removeEmptyAnchorsLinks%22%2C%22removeTrackingIDs%22%2C%22removeLocaleFromUrls%22%2C%22prefixUrlToFrenchVersions%22%5D%2C%22executeClientScripts%22%3Atrue%7D%7D%7D&destination=OpenTermsArchive%2Fsandbox&expertMode=true&step=2).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json).

**Comment by Ndpnt** [comment]
🤖 Closed automatically as version is unchanged but data has been fetched correctly

**Comment by Ndpnt** [comment]
🤖 Reopened automatically as an error occured

This document is no longer properly tracked. 

Error from the engine:

> ```InaccessibleContentError: The document cannot be accessed or its content can not be selected:
 - Timed out after 30 seconds when trying to fetch 'http://www.shockwave.com/about/privacyPolicy.jsp'```

Check what's wrong by:
- Using the [online contribution tool](https://contribute.opentermsarchive.org/en/service?json=%7B%22name%22%3A%22Facebook%22%2C%22documents%22%3A%7B%22Privacy+Policy%22%3A%7B%22fetch%22%3A%22https%3A%2F%2Ffr-fr.facebook.com%2Fprivacy%2Fexplanation%2F%22%2C%22select%22%3A%5B%22hr%2Bdiv%22%5D%2C%22filter%22%3A%5B%22removeEmptyAnchorsLinks%22%2C%22removeTrackingIDs%22%2C%22removeLocaleFromUrls%22%2C%22prefixUrlToFrenchVersions%22%5D%2C%22executeClientScripts%22%3Atrue%7D%7D%7D&destination=OpenTermsArchive%2Fsandbox&expertMode=true&step=2).


And some info about what has already been tracked:
- See [service declaration JSON file](https://github.com/OpenTermsArchive/sandbox/blob/main/declarations/Facebook.json).
